### ISSUE TITLE
Support of attrbutes

### ISSUE THREAD

**Issue by Grummfy** [hendrikmaus/reynaldo#6]
Hello,
there is a missing support for the attributes (https://apiblueprint.org/documentation/examples/09-advanced-attributes.html).

Anyone already working on it?

thanks

**Comment by hendrikmaus** [comment]
I do not have the capacity to work on it, help appreciated.

**Comment by Grummfy** [comment]
I will try something, then ;)

**Comment by Grummfy** [comment]
well in fact the data are already taken by the parser ... so this is there ;)
it's considered by drafter as a datastructure \o/

**Comment by hendrikmaus** [comment]
Nice, good news.
